/// <reference path="modernizr-2.6.2.js" />
/// <reference path="jquery-1.10.2.js" />
/// <reference path="bootstrap.js" />
/// <reference path="respond.js" />
/// <reference path= "jquery - vsdoc\2.1.0"/>
/// <reference path="wwwroot/lib/jquery/dist/jquery.js" />
/// <reference path="wwwroot/lib/jquery-validation/dist/jquery.validate.js" />
/// <reference path="wwwroot/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" />
/// <reference path="wwwroot/lib/jquery-validation/dist/additional-methods.js" />
/// <reference path="jquery-3.6.1.js" />
/// <reference path="../../../../../../../.nuget/packages/bootstrap/5.2.1/contentfiles/any/any/wwwroot/js/bootstrap.js" />
/// <reference path="wwwroot/lib/bootstrap/dist/js/bootstrap.js" />
